# Generated by Django 5.0.1 on 2024-02-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('time_spent', models.IntegerField(help_text='Time spent in conversation, in seconds')),
                ('chat_log', models.JSONField(help_text='JSON structure containing the chat log')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
