# Generated by Django 5.0.1 on 2024-04-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='message_type_log',
            field=models.JSONField(default='[]', help_text='JSON structure containing the message type log'),
            preserve_default=False,
        ),
    ]
