# Generated by Django 5.0.1 on 2024-04-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation_message_type_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='test_type',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
