# Generated by Django 4.2.20 on 2025-04-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_conversation_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='feel_level',
            field=models.CharField(default='High', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='problem_type',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='think_level',
            field=models.CharField(default='High', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='chat_log',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='message_type_log',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='test_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='time_spent',
            field=models.IntegerField(),
        ),
    ]
