# Generated by Django 4.2.10 on 2025-07-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_conversation_feel_level_conversation_problem_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='endpoint_type',
            field=models.TextField(default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='chat_log',
            field=models.JSONField(help_text='JSON structure containing the chat log'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='feel_level',
            field=models.CharField(default='High', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='message_type_log',
            field=models.JSONField(help_text='JSON structure containing the message type log'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='problem_type',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='test_type',
            field=models.TextField(default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='think_level',
            field=models.CharField(default='High', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='time_spent',
            field=models.IntegerField(help_text='Time spent in conversation, in seconds'),
        ),
    ]
